language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev"
  # - "pypy"
  # - "pypy3" # TODO: pkg_config issues

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "python setup.py develop"
  - "pipenv install --dev"
# command to run tests
script:
  # flake8 has dropped support for Python 2.6.
  - if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then pipenv run flake8; fi
  - pipenv run pytest tests
